# Generated by Django 2.0.4 on 2018-05-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CostosLigas',
            new_name='CostosLiga',
        ),
    ]
