# Generated by Django 2.0.5 on 2018-06-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0003_auto_20180604_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costosliga',
            name='tipo',
            field=models.CharField(choices=[('Soccer pasto natural y sintético', 'Soccer pasto natural y sintético'), ('Pasto sintético 7', 'Pasto sintético 7'), ('Pasto sintético 6 y rápido', 'Pasto sintético 6 y rápido'), ('Cemento fútbol rápido y 6', 'Cemento fútbol rápido y 6'), ('Soccer tierra', 'Soccer Tierra'), ('Multiusos', 'Multiusos')], max_length=35),
        ),
    ]
