# Generated by Django 2.0.3 on 2018-03-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=250)),
                ('ubicacion', models.CharField(max_length=500)),
                ('colonia', models.CharField(max_length=50)),
                ('zona', models.CharField(max_length=20)),
            ],
        ),
    ]
