# Generated by Django 2.0.3 on 2018-03-21 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_interna', models.CharField(max_length=300)),
                ('clave_cancha', models.CharField(max_length=10)),
                ('activa', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('costo', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cancha',
            name='tipo_cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unidad.Tipo_Cancha'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unidad.Unidad'),
        ),
    ]
