# Generated by Django 2.0.3 on 2018-03-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0002_auto_20180321_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_cancha',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
