# Generated by Django 2.0.4 on 2018-05-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0004_auto_20180331_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostosEscuelaExterna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CostosFutbolParticular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
            ],
        ),
    ]
