# Generated by Django 2.0.4 on 2018-05-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0005_costosescuelaexterna_costosfutbolparticular'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CostosFutbolParticular',
            new_name='CostosCanchaParticular',
        ),
    ]
