# Generated by Django 2.0.4 on 2018-05-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0006_auto_20180514_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostosCanchaParticular',
        ),
        migrations.DeleteModel(
            name='CostosEscuelaExterna',
        ),
    ]
