# Generated by Django 2.0.4 on 2018-05-14 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0008_auto_20180514_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_cancha',
            name='costo_liga_jyf',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='juvenilyfemenil', to='costos.CostosLiga'),
        ),
        migrations.AlterField(
            model_name='tipo_cancha',
            name='costo_liga_libre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='libre', to='costos.CostosLiga'),
        ),
        migrations.AlterField(
            model_name='tipo_cancha',
            name='liga_infantil',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='infantil', to='costos.CostosLiga'),
        ),
    ]
