# Generated by Django 2.0.4 on 2018-05-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0010_auto_20180514_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_cancha',
            name='costo',
        ),
    ]
