# Generated by Django 2.0.5 on 2018-06-04 14:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0002_auto_20180514_1759'),
        ('unidad', '0011_remove_tipo_cancha_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_cancha',
            name='costo_escuela',
        ),
        migrations.RemoveField(
            model_name='tipo_cancha',
            name='costo_liga_infantil',
        ),
        migrations.RemoveField(
            model_name='tipo_cancha',
            name='costo_liga_jyf',
        ),
        migrations.RemoveField(
            model_name='tipo_cancha',
            name='costo_liga_libre',
        ),
        migrations.RemoveField(
            model_name='tipo_cancha',
            name='costo_particular',
        ),
        migrations.AddField(
            model_name='cancha',
            name='costo_escuela',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='costos.CostosEscuelaExterna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancha',
            name='costo_liga_infantil',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='infantil', to='costos.CostosLiga'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='costo_liga_jyf',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='juvenilyfemenil', to='costos.CostosLiga'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='costo_liga_libre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='libre', to='costos.CostosLiga'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='costo_particular',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='costos.CostosCanchaParticular'),
            preserve_default=False,
        ),
    ]
