# Generated by Django 2.0.4 on 2018-04-26 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidad', '0004_auto_20180331_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalles_renta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descuento', models.IntegerField(default=0)),
                ('fecha_renta', models.DateField(auto_now=True)),
                ('tipo_renta', models.CharField(max_length=20)),
                ('renta_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unidad.Cancha')),
            ],
        ),
        migrations.AddField(
            model_name='detalles_renta',
            name='renta_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renta.Renta'),
        ),
    ]
