# Generated by Django 2.0.4 on 2018-05-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renta',
            old_name='renta_id',
            new_name='espacio_id',
        ),
    ]
