# Generated by Django 2.0.5 on 2018-06-18 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0004_auto_20180608_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='horas_totales',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='renta',
            name='contrato',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='renta.Contrato'),
        ),
        migrations.AlterField(
            model_name='renta',
            name='detalles',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='renta',
            name='especial',
            field=models.CharField(default='NO', max_length=255),
        ),
        migrations.AlterField(
            model_name='renta',
            name='status',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='renta',
            name='trimestre',
            field=models.IntegerField(default=None),
        ),
    ]
