# Generated by Django 2.0.5 on 2018-06-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0005_auto_20180618_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta',
            name='contrato',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='renta.Contrato'),
        ),
        migrations.AlterField(
            model_name='renta',
            name='costo',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='renta',
            name='detalles',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='renta',
            name='especial',
            field=models.CharField(blank=True, default='NO', max_length=255),
        ),
        migrations.AlterField(
            model_name='renta',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='renta',
            name='tipo_renta',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='renta',
            name='trimestre',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
