# Generated by Django 2.0.5 on 2018-06-18 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidad', '0012_auto_20180604_1428'),
        ('renta', '0006_auto_20180618_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renta',
            name='espacio_id',
        ),
        migrations.AddField(
            model_name='renta',
            name='espacio',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='unidad.Cancha'),
        ),
    ]
