# Generated by Django 2.0.5 on 2018-06-18 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0007_auto_20180618_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta',
            name='descuento',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='renta',
            name='espacio',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='unidad.Cancha'),
        ),
    ]
