# Generated by Django 2.0.5 on 2018-06-07 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.TextField(blank=True, max_length=200)),
                ('telefono', models.TextField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete='DO_NOTHING', related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
